resolver: lts-10.10
packages:
- .
- hs-generator
#- ../hs-yesod-model-generator

extra-deps:
- git: https://github.com/agreif/hs-yesod-model-generator.git
  commit: 7e3b3db41559704cdcb86174dceaeadaf12872cf

allow-newer: true

nix:
  enable: true
  pure: false
  packages:
    - zlib
    - bzip2
    - postgresql
